spring.cloud.config.enabled=false
spring.application.name=USER-CATALOG-SERVICE
server.port=${PORT}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-bean-definition-overriding=true
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.maximum-pool-size=25
spring.datasource.hikari.keepalive-time=30000

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=false

ghost.shield.jwt-secret=${JWT_SECRET}
ghost.shield.jwt-expiration=86400000

server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain
server.compression.min-response-size=1024

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_LOGIN_EMAIL}
spring.mail.password=${BREVO_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false