spring.application.name=user-catalog-service
server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3306/UserCatalogService
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#will tell this service where the Eureka Server is
eureka.client.enabled=true

eureka.instance.prefer-ip-address=true

spring.cloud.config.enabled=false


# Twilio Configuration
twilio.account-sid=AC2e3f16eafeac61c4edb0ea6a51112c92
twilio.auth-token=5d493684fd650ccf5ca6bc2e5ecdaac9
twilio.from-number=+12512373752

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adityakakade.skncoe.comp@gmail.com
spring.mail.password=rmzpoprhckdkccyb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Tell it where the Eureka Server is located
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Ensure it registers even if it thinks it's a standalone
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Make instances send a heartbeat every 5 seconds for rapid discovery
eureka.instance.lease-renewal-interval-in-seconds=5
# Allow 15 seconds before the registry expires an instance
eureka.instance.lease-expiration-duration-in-seconds=15

